name: PyInstaller compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: .
    - run: tree
    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: /dist/Linux
