name: PyInstaller compilation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Package Application - Pyinstaller
        run: pyinstaller main.py --onefile --name GnssLogger
      - name: Tree
        run: tree
      - name: Copy convbin.exe
        run: cp convbin.exe /dist/
      - uses: actions/upload-artifact@v2
        with:
          name: GnssLogger
          path: /dist/
